server:
  port: 8084

spring:
  application:
    name: MESSAGE-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/my_test
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:samarkand2004@@}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://${EUREKA_HOST:localhost}:8761/eureka/}
  instance:
    preferIpAddress: true

springdoc:
  swagger-ui:
    config-url: /api/message/v3/api-docs/swagger-config
    url: /api/message/swagger-ui
    path: /api/message/swagger-ui